Use cases for ECommerce
RedkeyD/ECommerce pull request #4
Opened 2024-07-04 07:49 UTC by RedkeyD

2024-07-05 08:01 UTC, SherlockD requested changes

2024-07-05 08:01 UTC, SherlockD commented on Application/Carts/Commands/AddProductToCart/AddProductToCartCommand.cs
> +        if ( cartId == Guid.Empty )
валидацию перенести в валидатор команды

2024-07-05 08:01 UTC, SherlockD commented on Application/Carts/Commands/RemoveProductFromCart/RemoveProductFromCartCommand.cs
> +public class RemoveProductFromCartCommand
record

2024-07-05 08:01 UTC, SherlockD commented on Domain/Entities/User.cs
> -    public string PasswordHash { get; private set; }
password hash

2024-07-05 08:01 UTC, SherlockD commented on Presentation/Program.cs
> +builder.Services.AddMediatR( typeof( GetUserQuery ).Assembly );
В проекте Application создать record AssemblyReference, использовать его здесь typeof( AssemblyReference).Assembly

2024-07-05 08:01 UTC, SherlockD commented on Presentation/Program.cs
> +builder.Services.AddMediatR( typeof( GetUserQuery ).Assembly );
почитатай как работает builder.Services.AddMediatR( typeof( GetUserQuery ).Assembly );

2024-07-05 08:01 UTC, SherlockD commented on Application/Products/Queries/GetProduct/GetProductQuery.cs
> +﻿namespace Application.Products.Queries.GetProduct;
namespace ниже юзингов

2024-07-05 08:01 UTC, SherlockD commented on Application/Reviews/Queries/GetReview/GetReviewQuery.cs
> +{
лишний Query

2024-07-05 12:00 UTC, SherlockD requested changes

2024-07-05 12:00 UTC, SherlockD commented on Application/Products/Queries/GetProduct/GetProductQueryHandler.cs
> +        var product = await _productRepository.GetByIdAsync( query.ProductId );
var -> type
так как мы не можем из контекста правой стороны выражения понять тип данных которое оно возвращает

2024-07-05 12:00 UTC, SherlockD commented on Application/Products/Queries/GetProduct/GetProductQueryHandler.cs
> +        var product = await _productRepository.GetByIdAsync( query.ProductId );
Не забудь в валидаторе проверить, что Product существует

2024-07-08 04:10 UTC, RedkeyD commented on Application/Products/Queries/GetProduct/GetProductQueryHandler.cs
> +        var product = await _productRepository.GetByIdAsync( query.ProductId );
а, исправлено :)

2024-07-08 04:10 UTC, RedkeyD commented on Application/Products/Queries/GetProduct/GetProductQueryHandler.cs
> +        var product = await _productRepository.GetByIdAsync( query.ProductId );
добавил проверку 
:)

2024-07-08 04:10 UTC, RedkeyD commented on Application/Reviews/Queries/GetReview/GetReviewQuery.cs
> +{
убрано

2024-07-08 04:11 UTC, Zievidinov commented on Application/Products/Queries/GetProduct/GetProductQuery.cs
> +﻿namespace Application.Products.Queries.GetProduct;
исправлено

2024-07-08 04:11 UTC, RedkeyD commented on Presentation/Program.cs
> +builder.Services.AddMediatR( typeof( GetUserQuery ).Assembly );
хорошо :)

2024-07-08 04:11 UTC, RedkeyD commented on Domain/Entities/User.cs
> -    public string PasswordHash { get; private set; }
вернул как было

2024-07-08 04:13 UTC, RedkeyD commented on Application/Carts/Commands/RemoveProductFromCart/RemoveProductFromCartCommand.cs
> +public class RemoveProductFromCartCommand
если делать тип рекорд, то он почему то валидатор не находить. Скрин в тг :)

2024-07-08 04:13 UTC, RedkeyD commented on Application/Carts/Commands/AddProductToCart/AddProductToCartCommand.cs
> +        if ( cartId == Guid.Empty )
сделано

2024-07-08 06:26 UTC, Alexander-Saveliev commented on Application/Carts/Commands/AddProductToCart/AddProductToCartCommand.cs
> +        AddProductToCartCommandValidator.ValidateCartId( cartId );
- [ ] Валидатор не должен быть статическим. Он должен имплементировать интерфейс и через интерфейс приниматься через конструктор класса ХЕНДЛЕРА
- [ ] Валидатор должен содержать один метод валидации всей команды

2024-07-08 06:45 UTC, Alexander-Saveliev requested changes

2024-07-08 06:45 UTC, Alexander-Saveliev commented on Application/Carts/Commands/AddProductToCart/AddProductToCartCommandValidator.cs
> +            throw new ArgumentException( "Cart ID cannot be empty", nameof( cartId ) );
- [ ] Бросать исключения не очень хорошая практика. Сделай дополнительный класс ошибки и в случае ошибки возвращай его

2024-07-15 05:56 UTC, SherlockD requested changes

2024-07-15 05:56 UTC, SherlockD commented on Application/Application.Admin/Application.Admin.csproj
> +    <ProjectReference Include="..\Application.Shop\Application.Shop.csproj" />
Нужно будет убрать зависимость на Application.Shop

2024-07-15 05:56 UTC, SherlockD commented on Application/Application.Shop/Carts/Commands/AddProductToCart/AddProductToCartCommandHandler.cs
> +
Перенос лишний

2024-07-15 05:56 UTC, SherlockD commented on Application/Application.Shop/Carts/Commands/AddProductToCart/AddProductToCartCommandHandler.cs
> +            await _cartRepository.UpdateAsync( cart );
Не нужен метод UpdateAsync, за обновление базы отвечает unitOfWork. Почитай про паттерн UnitOfWork в связке с EntityFramework и как EntityFramework сохраняет данные

2024-07-15 05:56 UTC, SherlockD commented on Application/Application.Shop/Carts/Queries/GetCart/GetCartQueryValidator.cs
> +            if ( data.CartId == default )
Где то Guid.Empty, где то defaul, нужно привести все к единообразному виду. Либо так, либо так

2024-07-15 05:56 UTC, SherlockD commented on Domain/Entities/Cart.cs
> +        public void RemoveProduct( Guid productId )
Давай все же не будем писать в DDD стиле, методы для работы с продуктом перенесем либо в сам продукт, либо в репозиторий, если нужно удалить, добавить сущности

2024-07-15 05:56 UTC, SherlockD commented on Domain/Errors/CartErrors.cs
> +    public static class CartErrors
Пустые классы, если не используются лучше удалить

2024-07-15 05:56 UTC, SherlockD commented on Infrastructure/Infrastructure/Foundation/EntityFramework/Configurations/CartConfiguration.cs
> +
пустая строка

2024-07-15 05:56 UTC, SherlockD commented on Infrastructure/Infrastructure/Foundation/EntityFramework/Configurations/CartConfiguration.cs
> +
Лучше добавить описание всех полей, может понадобится в будущем.

2024-07-15 05:56 UTC, SherlockD commented on Infrastructure/Infrastructure/Foundation/EntityFramework/Configurations/CartConfiguration.cs
> +namespace Infrastructure.Foundation.EntityFramework.Configurations
Структуру файлов для работы с сущностями лучше сделать как в application: Infrastructure/Carts/CartConfiguration.cs

2024-07-15 05:56 UTC, SherlockD commented on Infrastructure/Infrastructure/Foundation/EntityFramework/Configurations/UserConfiguration.cs
> +            builder.Property( u => u.Username ).HasMaxLength( 20 ).IsRequired();
Вот как тут(я про описание сущностей). Молодец что указал длину поля, это важно. Но нужно теперь в проверки в домене/апплекейшене указать проверки на длину поля, иначе будет падать непонятный Exception от EntityFramework

2024-07-15 05:56 UTC, SherlockD commented on Presentation/Presentation/Program.cs
>  var builder = WebApplication.CreateBuilder( args );
Солодец, что создал Presentation слой, но немножно неправильно, давай в этом пулреквесте сосредоточимся только на тех задачах, которые мы обсуждали и ставили. В целом не очень хорошая практика в один пулреквест много задач разношерстных пихать.

2024-07-15 05:56 UTC, SherlockD commented on Application/Application.Shop/Carts/Commands/AddProductToCart/AddProductToCartCommandHandler.cs
> +
В целом пробегись по всем файлам, много где лишние переносы есть

2024-07-15 07:08 UTC, RedkeyD commented on Application/Application.Admin/Application.Admin.csproj
> +    <ProjectReference Include="..\Application.Shop\Application.Shop.csproj" />
убрано

2024-07-15 07:24 UTC, RedkeyD commented on Application/Application.Shop/Carts/Queries/GetCart/GetCartQueryValidator.cs
> +            if ( data.CartId == default )
а, заметил, да, везде потсавил Guid.Empty теперь

2024-07-15 07:25 UTC, RedkeyD commented on Domain/Errors/CartErrors.cs
> +    public static class CartErrors
да, сейчас удалю

2024-07-15 07:44 UTC, RedkeyD commented on Application/Application.Shop/Carts/Commands/AddProductToCart/AddProductToCartCommandHandler.cs
> +
везде где нашел поправил по идее

2024-07-15 07:45 UTC, RedkeyD commented on Infrastructure/Infrastructure/Foundation/EntityFramework/Configurations/CartConfiguration.cs
> +
убрано

2024-07-15 08:07 UTC, RedkeyD commented on Infrastructure/Infrastructure/Foundation/EntityFramework/Configurations/CartConfiguration.cs
> +namespace Infrastructure.Foundation.EntityFramework.Configurations
да, изменил структуру

2024-07-15 08:21 UTC, RedkeyD commented on Presentation/Presentation/Program.cs
>  var builder = WebApplication.CreateBuilder( args );
а, хорошо

2024-07-15 09:43 UTC, RedkeyD commented on Infrastructure/Infrastructure/Foundation/EntityFramework/Configurations/CartConfiguration.cs
> +
добавил :)

2024-07-15 11:19 UTC, RedkeyD commented on Infrastructure/Infrastructure/Foundation/EntityFramework/Configurations/UserConfiguration.cs
> +            builder.Property( u => u.Username ).HasMaxLength( 20 ).IsRequired();
а можно узнать где именно в апликейшене, а так то вроде везде добавил проверку

2024-07-15 13:05 UTC, RedkeyD commented on Domain/Entities/Cart.cs
> +        public void RemoveProduct( Guid productId )
добавил в репозиторий отдельный :)

2024-07-15 13:07 UTC, RedkeyD commented on Application/Application.Shop/Carts/Commands/AddProductToCart/AddProductToCartCommandHandler.cs
> +            await _cartRepository.UpdateAsync( cart );
убрал :)

2024-07-16 05:54 UTC, SherlockD requested changes

2024-07-16 05:54 UTC, SherlockD commented on Application/Application.Shop/Carts/Commands/UpdateProductQuantityInCart/UpdateProductQuantityInCartCommandHandler.cs
> +            _cartRepository.Update(cart);
Зачем метод Update в репозитории?

2024-07-16 05:54 UTC, SherlockD commented on Domain/Entities/Cart.cs
> +        public void RemoveProduct( Guid productId )
Хорошо, но почему эти методы тут остались?)

2024-07-16 06:01 UTC, RedkeyD commented on Domain/Entities/Cart.cs
> +        public void RemoveProduct( Guid productId )
кхм, забыл убрать

2024-07-16 12:57 UTC, SherlockD requested changes

2024-07-16 12:57 UTC, SherlockD commented on Domain/Entities/Product.cs
> +
!!!

2024-07-16 12:57 UTC, SherlockD commented on Infrastructure/Infrastructure/Carts/CartConfiguration.cs
> +            builder.Property( c => c.UserId ).HasColumnName( nameof( Cart.UserId ) ).IsRequired();
Нужно преобразовать в вид user_id и другие поля в других таблицах также. Также название таблицы нужно писать в виде user, cart, cart_item.

2024-07-16 12:57 UTC, SherlockD commented on Infrastructure/Infrastructure/Categories/CategoryConfiguration.cs
> +
!!!!

2024-07-16 12:57 UTC, SherlockD commented on Infrastructure/Infrastructure/OrderItems/OrderItemConfiguration.cs
> +
!!!! давай внимательнее, часто такие ошибки попадаются

2024-07-16 12:57 UTC, SherlockD commented on Infrastructure/Infrastructure/Reviews/ReviewConfiguration.cs
> +
Посмотри везде

2024-07-16 13:48 UTC, SherlockD requested changes

2024-07-16 13:48 UTC, SherlockD commented on Infrastructure/Infrastructure/Reviews/ReviewConfiguration.cs
> +            builder.HasKey( r => r.Id );
id, publicid тоже нужно название с маленькой буквы

2024-07-17 05:59 UTC, SherlockD approved these changes

2024-07-17 06:13 UTC, merged